### PR TITLE
add fake furnace daemon

### PR DESCRIPTION
**Pull request by untzag**
- [x] changelog
- [x] tests

### CODE REVIEW

**Comment by kameyer226** [comment]
looking at it

**Comment by kameyer226** [comment]
installed yaqd-control and yaqd-python elements in separate conda env, cannot find yaqd-fake-furnace.  Does yaqd-control require an update to hatch for this to work?   Or am I missing a hatch command?  (I do not see yaqd-fakes or yaqd-control in `conda list` when I do a hatch build.)

**Comment by kameyer226** [comment]
Sorry I do not see yaqd-core or yaqd-fakes, I can see yaqd-control because I conda installed that.

**Comment by untzag** [comment]
Try `python -m pip install -e .`

**Review by kameyer226 — APPROVED** [review]

**Pull request merged**
