### PR TITLE
Fake has transformed position

### LINKED ISSUE #56: HasTransformedPosition: limits is broken
Currently, limits mixes up native and transformed limits when checking what positions are valid.

e.g. 
position  = 2 * native
limits = [1, 2]  (this should apply to transformed position)

calling `set_native_position(0.5)` will actually set the native position to 1, and the transformed position to 1.5

In addition to fixing this bug (native should only check limits in native coordinates), I propose to add new config params for the trait that allow setting limits in native position.  In software, we will always restrict movement to the intersection of valid native positions and transformed positions.

### PR DESCRIPTION
**Pull request by kameyer226**
Closes #56 .

### CODE REVIEW

**Comment by ddkohler** [comment]
Great work @kameyer226!  Before I review can you also add some tests for your new fake hardware?  The tests folder has a lot of examples of how other fake hardware can be run and tested.  Having some tests will demonstrate confidence in this daemon's implementation.  I'm happy to provide some assertions that we could put in tests if you are looking for good questions to ask of the daemon.

**Comment by kameyer226** [comment]
need yaq-traits updated on repository to perform tests

**Comment by ddkohler** [comment]
A MR for yaq-traits has been submitted; we should be able to use the revised trait shortly.  When released, update version of yaq-traits in `.pre-commit-config.yaml` and we should be good to go.

I played with the fake daemon a little bit--I tested it with
```
    assert np.isclose(c.get_limits(), [1.0, 4.0])
```
which currently fails.  Daemon reports the limits as (`[0,6]`).

**Review by ddkohler — APPROVED** [review]
we should bump version after this

**Pull request merged**
